# Generated by Django 4.2.1 on 2023-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('items', models.TextField()),
                ('lat_long', models.CharField(max_length=500)),
                ('full_details', models.TextField()),
            ],
        ),
    ]
